name: Release
on:
# every morning
#  schedule:
#    - cron:  '0 12 * * 1-4'

# manual trigger
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.version != null }}
    steps:
      - name: Version
        run: echo "${{ github.event.inputs.version }}"

      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Forked Uniswap SDK
        run: yarn --cwd "./uniswap-sdk" install --frozen-lockfile

      - name: Build Forked Uniswap SDK
        run: yarn --cwd "./uniswap-sdk" build

      - name: Add Forked Uniswap SDK
        run: yarn add ./uniswap-sdk

      - name: Build the IPFS bundle
        run: yarn build

      - name: Pin to IPFS
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@39bbda1ce1fe24c69c6f57861b8038278d53688d
        with:
          pin-name: Celswap ${{ github.event.inputs.version}}
          path: './build'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}

      - name: Convert CIDv0 to CIDv1
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@v1.0.0
        with:
          cidv0: ${{ steps.upload.outputs.hash }}

      - name: Update DNS with new IPFS hash
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: 'celswap.org'
          RECORD_NAME: '_dnslink.app'
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: textileio/cloudflare-update-dnslink@0fe7b7a1ffc865db3a4da9773f0f987447ad5848
        with:
          cid: ${{ steps.upload.outputs.hash }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ steps.upload.outputs.hash }}`
            - CIDv1: `${{ steps.convert_cidv0.outputs.cidv1 }}`

            The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [app.celswap.org](https://app.celswap.org).

            You can also access the Celswap interface directly from an IPFS gateway.
            The Celswap interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to store your settings.
            **Beware** that other sites you access via the _same_ IPFS gateway can read and modify your settings on the Celswap interface without your permission.
            You can avoid this issue by using a subdomain IPFS gateway, or our alias to the latest release at [app.celswap.org](https://app.celswap.org).
            The preferred URLs below are safe to use to access this specific release.

            Preferred URLs:
            - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.dweb.link/
            - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.cf-ipfs.com/
            - [ipfs://${{ steps.upload.outputs.hash }}/](ipfs://${{ steps.upload.outputs.hash }}/)

            Other IPFS gateways:
            - https://cloudflare-ipfs.com/ipfs/${{ steps.upload.outputs.hash }}/
            - https://ipfs.infura.io/ipfs/${{ steps.upload.outputs.hash }}/
            - https://ipfs.io/ipfs/${{ steps.upload.outputs.hash }}/
